name: Bottles

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  check-formula:
    runs-on: macos-latest
    name: Prepare for Bottling
    steps:
      - name: Check Commit Author
        run: |
          if [ "${{ github.event.pusher.username }}" == "github-actions[bot]" ]; then
            echo "This commit was made by a bot. Exiting..."
            exit 1
          fi

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get Updated Formula
        id: updated-formula
        uses: tj-actions/changed-files@v34
        with:
          files: |
            Formula/*.rb

      - name: Was a Formula Updated?
        run: |
          if [ "${{ steps.updated-formulae.outputs.any_changed }}" == "false" ]; then
            echo "No formulae were updated, skipping bottle build."
            exit 0
          fi

    outputs:
      formula: ${{ steps.updated-formulae.outputs.all_changed_files }}

  build-bottles:
    name: Build Bottles
    needs: check-formula
    strategy:
      matrix:
        os: [macos-11, macos-12, macos-latest]
        formulae: [emdy.rb]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Set Up Docker
        uses: docker-practice/actions-setup-docker@master

      - name: Authenticate to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Bottles
        run: |
          brew tap celsiusnarhwal/htt
          for formula in ${{ matrix.formulae }}; do
            formula_name="$(basename "$formula" .rb)"
            root_url="https://ghcr.io/v2/celsiusnarhwal/htt"
          
            brew install --build-bottle "$(basename "$formula" .rb)"
            brew bottle --json "$(basename "$formula" .rb)"
            
            json_file=$(find . -name "*.json")
            brew bottle --merge --write "$json_file" --root-url="$root_url"
            
            bottle=$(find . -name "$formula_name*.tar.gz")
            version=$(echo "$bottle" | sed -E "s/.*$formula_name-([0-9.]+)\.tar\.gz/\1/")
            sha256=$(docker import "$bottle" | sed -E "s/.*sha256:(.*)/\1/")
            docker tag "$sha256" "$root_url/$formula_name:$version@sha256:$sha256"
            docker push "$sha256"
          done

      - name: Upload Bottles
        uses: actions/upload-artifact@v3
        with:
          name: bottles
          path: "*.tar.gz"
