on:
  push:
    branches:
      - main

  workflow_dispatch:


jobs:
  build-bottles:
    runs-on: macos-latest
    name: Build Bottles
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Set Up Python
        uses: actions/setup-python@v2

      - name: Get Updated Formulae
        id: updated-formulae
        uses: tj-actions/changed-files@v34
        with:
          files: |
            Formula/*.rb

      - name: Build Bottles for Updated Formulae
        if: steps.updated-formulae.outputs.changed == 'true'
        run: |
          for file in ${{ steps.updated-formulae.outputs.all_changed_files }}; do
            ./.github/workflows/scripts/bottle.sh $(basename $file)
          done
          
          mv *.tar.gz Bottles/
          mv $(brew --prefix)/Library/Taps/celsiusnarhwal/homebrew-htt/Formula/*.rb Formula/