name: Bottles

on:
  push:
    branches:
      - main

  workflow_dispatch:


jobs:
  check-formulae:
    runs-on: macos-latest
    name: Prepare for Bottling
    steps:
      - name: Check Commit Author
        run: |
          if [ "${{ github.event.pusher.username }}" == "github-actions[bot]" ]; then
            echo "This commit was made by a bot. Exiting..."
            exit 1
          fi

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get Updated Formulae
        id: updated-formulae
        uses: tj-actions/changed-files@v34
        with:
          files: |
            Formula/*.rb

      - name: Were Formulae Updated?
        run: |
          if [ "${{ steps.updated-formulae.outputs.any_changed }}" == "false" ]; then
            echo "No formulae were updated, skipping bottle build."
            exit 1 
          fi

    outputs:
      formulae: ${{ steps.updated-formulae.outputs.all_changed_files }}

  bottle-macos-11:
    name: Bottle for macOS Big Sur
    needs: check-formulae
    runs-on: macos-11

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          path: houkago-tea-tap
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Commmit Author to GitHub Actions
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Build Bottles
        run: |
          cd houkago-tea-tap
          chmod +x ./bottle.sh && ./bottle.sh ${{ needs.check-formulae.outputs.formulae }}

  bottle-macos-12:
    name: Bottle for macOS Monterey
    needs: check-formulae
    runs-on: macos-12

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          path: houkago-tea-tap
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Commmit Author to GitHub Actions
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Build Bottles
        run: |
          cd houkago-tea-tap
          chmod +x ./bottle.sh && ./bottle.sh ${{ needs.check-formulae.outputs.formulae }}

  bottle-macos-latest:
    name: Bottle for Latest macOS
    needs: check-formulae
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          path: houkago-tea-tap
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Commmit Author to GitHub Actions
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Build Bottles
        run: |
          cd houkago-tea-tap
          chmod +x ./bottle.sh && ./bottle.sh ${{ needs.check-formulae.outputs.formulae }}

          


