name: Bottles

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  check-formulae:
    runs-on: ubuntu-latest
    name: Prepare for Bottling
    steps:
      - name: Check Commit Author
        run: |
          if [ "${{ github.event.pusher.username }}" == "github-actions[bot]" ]; then
            echo "This commit was made by a bot. Exiting..."
            exit 1
          fi

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get Updated Formulae
        id: updated-formulae
        uses: tj-actions/changed-files@v34
        with:
          files: |
            Formula/*.rb

      - name: Were Formulae Updated?
        run: |
          if [ ${{ steps.updated-formulae.outputs.any_changed }} == "false" ]; then
            echo "No formulae were updated, skipping bottle build."
            exit 1
          fi
    outputs:
        formulae: ${{ steps.updated-formulae.outputs.all_changed_files }}

  build-bottles:
    name: Bottle Formulae
    needs: check-formulae
    runs-on: macos-12
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          path: htt

      - name: Set Commit Author to GitHub Actions
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Bottle Formula
        run: |
          brew tap celsiusnarhwal/htt
          
          for f in ${{ needs.check-formulae.outputs.formulae }}; do
            formula=$(basename $f .rb)
          
            brew install --build-bottle $formula
            brew bottle --json $formula
            brew bottle --write --merge --no-commit $formula*.json
            brew pr-upload --root-url="https://ghcr.io/v2/celsiusnarhwal/htt"
            rm *.tar.gz *.json
            
            brew cd celsiusnarhwal/htt
            cp -rf Formula/$formula.rb /htt/Formula
            cd /htt
            git pull --rebase
            git push
          done
        env:
          GITHUB_TOKEN: ${{ github.token }}
          HOMEBREW_GITHUB_PACKAGES_USER: ${{ github.repository_owner }}
          HOMEBREW_GITHUB_PACKAGES_TOKEN: ${{ github.token }}