name: Bottles

on:
#  push:
#    branches:
#      - main

  workflow_dispatch:

jobs:
  check-formulae:
    runs-on: macos-latest
    name: Prepare for Bottling
    steps:
      - name: Check Commit Author
        run: |
          if [ "${{ github.event.pusher.username }}" == "github-actions[bot]" ]; then
            echo "This commit was made by a bot. Exiting..."
            exit 1
          fi

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get Updated Formulae
        id: updated-formulae
        uses: tj-actions/changed-files@v34
        with:
          files: |
            Formula/*.rb

      - name: Were Formulae Updated?
        run: |
          if [ ${{ steps.updated-formulae.outputs.any_changed }} == "false" ]; then
            echo "No formulae were updated, skipping bottle build."
            exit 1
          fi

      - name: Set Formulae Matrix
        id: set-matrix
        run: | 
          echo "matrix={
            \"os\": [\"macos-11\", \"macos-12\"],
            \"formulae\": echo [${{ steps.updated-formula.outputs.all_changed_files }} | sed \"s/ /, /g\"]
          }"
    outputs:
        matrix: ${{ steps.set-matrix.outputs.matrix }}

  build-bottles:
    name: Bottle Formulae
    needs: check-formulae
    strategy:
      matrix:
        ${{ fromJson(needs.check-formulae.outputs.matrix) }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v2

      - name: Set Up docker
        uses: docker-practice/actions-setup-docker@master

      - name: Set Commit Author to GitHub Actions
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Bottle Formula
        run: |
          formula="$(basename "${{ matrix.formula }}" .rb)"
          
          brew tap celsiusnarhwal/htt
          brew install --build-bottle "$formula"
          brew bottle --json "$formula"
          
          python bottlejson.py
          rm *.tar.gz *.json
          
          brew cd celsiusnarhwal/htt
          echo "$PWD"
          git pull --rebase
          git push