name: Bottles

on:
  push:
    branches:
      - main

  workflow_dispatch:

env:
  ROOT_URL: https://github.com/celsiusnarhwal/htt

jobs:
  check-formulae:
    runs-on: macos-latest
    name: Prepare for Bottling
    steps:
      - name: Check Commit Author
        run: |
          if [ "${{ github.event.pusher.username }}" == "github-actions[bot]" ]; then
            echo "This commit was made by a bot. Exiting..."
            exit 1
          fi

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get Updated Formulae
        id: updated-formulae
        uses: tj-actions/changed-files@v34
        with:
          files: |
            Formula/*.rb

      - name: Were Formulae Updated?
        run: |
          if [ "${{ steps.updated-formulae.outputs.any_changed }}" == "false" ]; then
            echo "No formulae were updated, skipping bottle build."
            exit 1 
          fi

    outputs:
      formulae: ${{ steps.updated-formulae.outputs.all_changed_files }}

  build-bottles:
    name: Build Bottles
    needs: check-formulae
    strategy:
      matrix:
        os: [macos-11, macos-12, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Build Bottles
        run: |
          for formula in ${{ needs.check-formulae.outputs.formulae }}; do
            brew install --build-bottle $formula
            brew bottle $formula
            
            json_file=$(find . -name $formula*.json)
            brew bottle --merge --write $json_file --root-url ${{ env.ROOT_URL }}
          done

      - name: Upload Bottles
        uses: actions/upload-artifact@v3
        with:
          name: bottles
          path: ./*.tar.gz

  push-bottles:
    name: Push Bottles
    needs: build-bottles
    runs-on: ubuntu-latest

    steps:
      - name: Download Bottles
        uses: actions/download-artifact@v3
        with:
          name: bottles
          path: .

      - name: Authenticate to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to GHCR
        run: |
          bottles=$(find . -name *.tar.gz)
          for bottle in $bottles; do
            formula_name=$(echo $bottle | cut -d'/' -f2 | cut -d'-' -f1)
            version=$(echo "$bottle" | sed -E "s/.*$formula_name-([0-9.]+)\.tar\.gz/\1/")
            root_url = ${{ env.ROOT_URL }}
          
            sha256=$(docker import "$bottle" | sed -E "s/.*sha256:(.*)/\1/")
            docker tag "$sha256" "$root_url/$formula_name:$version@sha256:$sha256"
            docker push "$root-url/$formula_name:$version@sha256:$sha256"
          done

            



          


