name: Bottles

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  check-formulae:
    runs-on: ubuntu-latest
    name: Prepare for Bottling
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get Updated Formulae
        id: updated-formulae
        uses: tj-actions/changed-files@v34
        with:
          files: |
            Formula/*.rb
    outputs:
      formulae: ${{ steps.updated-formulae.outputs.all_changed_files }}

  build-bottles:
    name: Bottle Formulae
    if: ${{ needs.check-formulae.outputs.formulae }}
    concurrency: bottles
    strategy:
      matrix:
        os: [ macos-11, macos-12 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set Up Python
        uses: actions/setup-python@v2

      - name: Set Commit Author to GitHub Actions
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Tap HTT
        run: |
          brew tap celsiusnarhwal/htt
          echo "TAP=$(brew --repo celsiusnarhwal/htt)" >> $GITHUB_ENV

      - name: Bottle Formulae
        run: |
          for formula in ${{ needs.check-formulae.outputs.formulae }}; do
            "$(brew --repo celsiusnarhwal/htt)/bottle.sh" "$formula" ${{ matrix.os }}
          done
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Push Formulae Changes
        uses: Homebrew/actions/git-try-push@master
        with:
          token: ${{ github.token }}
          directory: ${{ env.TAP }}
          branch: main
          tries: 1
