name: Bottles

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  check-formulae:
    runs-on: ubuntu-latest
    name: Prepare for Bottling
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get Updated Formulae
        id: updated-formulae
        uses: tj-actions/changed-files@v34
        with:
          files: |
            Formula/*.rb
    outputs:
      formulae: ${{ steps.updated-formulae.outputs.all_changed_files }}

  build-bottles:
    name: Bottle Formulae
    needs: check-formulae
    if: ${{ needs.check-formulae.outputs.formulae }}
    strategy:
      matrix:
        os: [ macos-11, macos-12 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Tap HTT
        run: |
          brew tap celsiusnarhwal/htt
          echo "TAP=$(brew --repo celsiusnarhwal/htt)" >> $GITHUB_ENV

      - name: Bottle Formulae
        run: |
          for formula in ${{ needs.check-formulae.outputs.formulae }}; do
            python3 "${{ env.TAP }}/scripts/mio.py" "$formula" ${{ matrix.os }}
          done
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Upload JSON Files
        uses: actions/upload-artifact@v3
        with:
          name: json
          path: ${{ env.TAP }}/*.json

  update-formulae:
    name: Update Formulae
    needs: build-bottles
    runs-on: macos-latest
    steps:
      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Tap HTT
        run: |
          brew tap celsiusnarhwal/htt
          echo "TAP=$(brew --repo celsiusnarhwal/htt)" >> $GITHUB_ENV

      - name: Download JSON Files
        uses: actions/download-artifact@v3
        with:
          name: json
          path: ${{ env.TAP }}

      - name: Write Bottle Blocks
        run: |
          for formula in ${{ needs.build-bottles.needs.check-formulae.outputs.formulae }}; do
            brew bottle --merge --write $(python3 "${{ env.TAP }}/scripts/ritsu.py" "$formula")
          done
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Push Formulae Changes
        uses: Homebrew/actions/git-try-push@master
        with:
          token: ${{ github.token }}
          directory: ${{ env.TAP }}
          branch: main
          tries: 1

